-- ============================================================================
-- PROJECT: NovaKart Retail – End-to-End Retail Data Analytics Platform
-- SCRIPT: Complete Snowflake Analytics Layer (Views, KPIs, Business Queries)
-- DATABASE: NOVAKART_DB
-- SCHEMA: ANALYTICS
-- WAREHOUSE: COMPUTE_WH
-- ============================================================================

USE DATABASE NOVAKART_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================================
-- PHASE 1: TABLE QUALITY CHECK & DATA PROFILING
-- ============================================================================

-- 1. Table Structure Inspection
DESCRIBE TABLE NOVAKART_DB.ANALYTICS.SALES;
DESCRIBE TABLE NOVAKART_DB.ANALYTICS.CUSTOMERS;
DESCRIBE TABLE NOVAKART_DB.ANALYTICS.PRODUCTS;
DESCRIBE TABLE NOVAKART_DB.ANALYTICS.EMPLOYEES;
DESCRIBE TABLE NOVAKART_DB.ANALYTICS.FINANCE;
DESCRIBE TABLE NOVAKART_DB.ANALYTICS.INVENTORY;

-- 2. Row Counts Verification
SELECT 'SALES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM NOVAKART_DB.ANALYTICS.SALES
UNION ALL SELECT 'CUSTOMERS', COUNT(*) FROM NOVAKART_DB.ANALYTICS.CUSTOMERS
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM NOVAKART_DB.ANALYTICS.PRODUCTS
UNION ALL SELECT 'EMPLOYEES', COUNT(*) FROM NOVAKART_DB.ANALYTICS.EMPLOYEES
UNION ALL SELECT 'FINANCE', COUNT(*) FROM NOVAKART_DB.ANALYTICS.FINANCE
UNION ALL SELECT 'INVENTORY', COUNT(*) FROM NOVAKART_DB.ANALYTICS.INVENTORY;

-- 3. Null & Data Quality Checks
SELECT 
    (SELECT COUNT(*) FROM SALES WHERE Sale_ID IS NULL OR Revenue IS NULL) AS SALES_NULLS,
    (SELECT COUNT(*) FROM CUSTOMERS WHERE Customer_ID IS NULL OR Email IS NULL) AS CUSTOMERS_NULLS,
    (SELECT COUNT(*) FROM PRODUCTS WHERE Product_ID IS NULL OR Selling_Price IS NULL) AS PRODUCTS_NULLS,
    (SELECT COUNT(*) FROM EMPLOYEES WHERE Employee_ID IS NULL OR Salary IS NULL) AS EMPLOYEES_NULLS,
    (SELECT COUNT(*) FROM FINANCE WHERE Transaction_ID IS NULL OR Net_Profit IS NULL) AS FINANCE_NULLS,
    (SELECT COUNT(*) FROM INVENTORY WHERE Inventory_ID IS NULL OR Current_Stock IS NULL) AS INVENTORY_NULLS;

-- 4. Duplicate Primary Key Checks
SELECT 'SALES' AS TABLE_NAME, COUNT(Sale_ID) - COUNT(DISTINCT Sale_ID) AS DUPLICATE_COUNT FROM SALES
UNION ALL SELECT 'CUSTOMERS', COUNT(Customer_ID) - COUNT(DISTINCT Customer_ID) FROM CUSTOMERS
UNION ALL SELECT 'PRODUCTS', COUNT(Product_ID) - COUNT(DISTINCT Product_ID) FROM PRODUCTS
UNION ALL SELECT 'EMPLOYEES', COUNT(Employee_ID) - COUNT(DISTINCT Employee_ID) FROM EMPLOYEES
UNION ALL SELECT 'FINANCE', COUNT(Transaction_ID) - COUNT(DISTINCT Transaction_ID) FROM FINANCE
UNION ALL SELECT 'INVENTORY', COUNT(Inventory_ID) - COUNT(DISTINCT Inventory_ID) FROM INVENTORY;

-- 5. Validation Status Check
SELECT 'SALES' AS TABLE_NAME, Validation_Status, COUNT(*) AS CNT FROM SALES GROUP BY 1, 2
UNION ALL SELECT 'CUSTOMERS', Validation_Status, COUNT(*) FROM CUSTOMERS GROUP BY 1, 2
UNION ALL SELECT 'PRODUCTS', Validation_Status, COUNT(*) FROM PRODUCTS GROUP BY 1, 2
UNION ALL SELECT 'EMPLOYEES', Validation_Status, COUNT(*) FROM EMPLOYEES GROUP BY 1, 2
UNION ALL SELECT 'FINANCE', Validation_Status, COUNT(*) FROM FINANCE GROUP BY 1, 2
UNION ALL SELECT 'INVENTORY', Validation_Status, COUNT(*) FROM INVENTORY GROUP BY 1, 2;

-- ============================================================================
-- PHASE 2: ANALYTICAL VIEWS
-- ============================================================================

-- 1. VW_SALES_PROFIT_ANALYSIS
CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_SALES_PROFIT_ANALYSIS AS
SELECT 
    Sale_ID,
    Date,
    Customer_ID,
    Product_ID,
    Branch,
    Quantity,
    Unit_Price,
    Discount,
    Cost,
    Revenue,
    Profit,
    ZEROIFNULL(ROUND((Profit / NULLIF(Revenue, 0)) * 100, 2)) AS PROFIT_MARGIN_PCT
FROM NOVAKART_DB.ANALYTICS.SALES;

-- 2. VW_PRODUCT_PERFORMANCE
CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_PRODUCT_PERFORMANCE AS
SELECT 
    p.Product_ID,
    p.Product_Name,
    p.Category,
    p.Brand,
    p.Cost_Price,
    p.Selling_Price,
    COALESCE(SUM(s.Quantity), 0) AS TOTAL_QUANTITY_SOLD,
    COALESCE(SUM(s.Revenue), 0) AS TOTAL_REVENUE,
    COALESCE(SUM(s.Profit), 0) AS TOTAL_PROFIT,
    ZEROIFNULL(ROUND(AVG(s.Unit_Price), 2)) AS AVG_SELLING_PRICE,
    ZEROIFNULL(ROUND((SUM(s.Profit) / NULLIF(SUM(s.Revenue), 0)) * 100, 2)) AS PROFIT_MARGIN_PCT
FROM NOVAKART_DB.ANALYTICS.PRODUCTS p
LEFT JOIN NOVAKART_DB.ANALYTICS.SALES s ON p.Product_ID = s.Product_ID
GROUP BY p.Product_ID, p.Product_Name, p.Category, p.Brand, p.Cost_Price, p.Selling_Price;

-- 3. VW_CUSTOMER_ANALYSIS
CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_CUSTOMER_ANALYSIS AS
SELECT 
    c.Customer_ID,
    c.Customer_Name,
    c.Email,
    c.City,
    c.State,
    c.Customer_Segment,
    c.Loyalty_Status,
    COUNT(s.Sale_ID) AS TOTAL_ORDERS,
    COALESCE(SUM(s.Quantity), 0) AS TOTAL_QUANTITY_PURCHASED,
    COALESCE(SUM(s.Revenue), 0) AS TOTAL_REVENUE,
    COALESCE(SUM(s.Profit), 0) AS TOTAL_PROFIT,
    ZEROIFNULL(ROUND(AVG(s.Revenue), 2)) AS AVG_ORDER_VALUE
FROM NOVAKART_DB.ANALYTICS.CUSTOMERS c
LEFT JOIN NOVAKART_DB.ANALYTICS.SALES s ON c.Customer_ID = s.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name, c.Email, c.City, c.State, c.Customer_Segment, c.Loyalty_Status;

-- 4. VW_INVENTORY_ANALYSIS
CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_INVENTORY_ANALYSIS AS
SELECT 
    Inventory_ID,
    Product_ID,
    Warehouse,
    Current_Stock,
    Minimum_Stock,
    Maximum_Stock,
    Stock_Status,
    ZEROIFNULL(ROUND((Current_Stock / NULLIF(Maximum_Stock, 0)) * 100, 2)) AS STOCK_LEVEL_PCT,
    CASE 
        WHEN Current_Stock < Minimum_Stock THEN 'REORDER_REQUIRED'
        ELSE 'STOCK_OK' 
    END AS REORDER_FLAG
FROM NOVAKART_DB.ANALYTICS.INVENTORY;

-- 5. VW_FINANCE_SUMMARY
CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_FINANCE_SUMMARY AS
SELECT 
    Transaction_ID,
    Date,
    Department,
    Revenue,
    Expenses,
    Tax,
    Profit,
    Net_Profit,
    Validation_Status,
    ZEROIFNULL(ROUND((Net_Profit / NULLIF(Revenue, 0)) * 100, 2)) AS NET_PROFIT_MARGIN_PCT
FROM NOVAKART_DB.ANALYTICS.FINANCE;

-- 6. VW_EMPLOYEE_ANALYSIS
CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_EMPLOYEE_ANALYSIS AS
SELECT 
    Employee_ID,
    Name AS EMPLOYEE_NAME,
    Department,
    Role AS DESIGNATION,
    Salary,
    Performance_Score,
    Validation_Status,
    CASE 
        WHEN Performance_Score >= 4 THEN 'Top Performer'
        WHEN Performance_Score = 3 THEN 'Average'
        ELSE 'Needs Improvement' 
    END AS PERFORMANCE_TIER
FROM NOVAKART_DB.ANALYTICS.EMPLOYEES;

-- ============================================================================
-- PHASE 3: BUSINESS KPI VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_RETAIL_KPI_SUMMARY AS
SELECT 
    (SELECT COALESCE(SUM(Revenue), 0) FROM NOVAKART_DB.ANALYTICS.SALES) AS TOTAL_REVENUE,
    (SELECT COALESCE(SUM(Cost), 0) FROM NOVAKART_DB.ANALYTICS.SALES) AS TOTAL_COST,
    (SELECT COALESCE(SUM(Profit), 0) FROM NOVAKART_DB.ANALYTICS.SALES) AS TOTAL_PROFIT,
    ZEROIFNULL(ROUND(((SELECT SUM(Profit) FROM NOVAKART_DB.ANALYTICS.SALES) / NULLIF((SELECT SUM(Revenue) FROM NOVAKART_DB.ANALYTICS.SALES), 0)) * 100, 2)) AS PROFIT_MARGIN_PCT,
    (SELECT COUNT(*) FROM NOVAKART_DB.ANALYTICS.SALES) AS TOTAL_SALES_COUNT,
    (SELECT COUNT(*) FROM NOVAKART_DB.ANALYTICS.CUSTOMERS) AS TOTAL_CUSTOMERS_COUNT,
    (SELECT COUNT(*) FROM NOVAKART_DB.ANALYTICS.PRODUCTS) AS TOTAL_PRODUCTS_COUNT,
    (SELECT COUNT(*) FROM NOVAKART_DB.ANALYTICS.EMPLOYEES) AS TOTAL_EMPLOYEES_COUNT,
    (SELECT COUNT(*) FROM NOVAKART_DB.ANALYTICS.INVENTORY) AS TOTAL_INVENTORY_ITEMS,
    (SELECT COUNT(*) FROM NOVAKART_DB.ANALYTICS.INVENTORY WHERE Current_Stock < Minimum_Stock) AS LOW_STOCK_ITEMS_COUNT;

-- ============================================================================
-- PHASE 4: BUSINESS ANALYTICS QUERIES (QUESTIONS 1 - 15)
-- ============================================================================

-- Q1: Total Revenue
SELECT SUM(Revenue) AS TOTAL_REVENUE FROM NOVAKART_DB.ANALYTICS.SALES;

-- Q2: Total Profit
SELECT SUM(Profit) AS TOTAL_PROFIT FROM NOVAKART_DB.ANALYTICS.SALES;

-- Q3: Overall Profit Margin (%)
SELECT ZEROIFNULL(ROUND((SUM(Profit) / NULLIF(SUM(Revenue), 0)) * 100, 2)) AS OVERALL_PROFIT_MARGIN_PCT 
FROM NOVAKART_DB.ANALYTICS.SALES;

-- Q4: Products Generating Highest Revenue
SELECT Product_ID, SUM(Revenue) AS REVENUE
FROM NOVAKART_DB.ANALYTICS.SALES
GROUP BY Product_ID
ORDER BY REVENUE DESC;

-- Q5: Products Generating Highest Profit
SELECT Product_ID, SUM(Profit) AS PROFIT
FROM NOVAKART_DB.ANALYTICS.SALES
GROUP BY Product_ID
ORDER BY PROFIT DESC;

-- Q6: Customers Generating Highest Revenue
SELECT Customer_ID, SUM(Revenue) AS REVENUE
FROM NOVAKART_DB.ANALYTICS.SALES
GROUP BY Customer_ID
ORDER BY REVENUE DESC;

-- Q7: Branches Generating Highest Revenue
SELECT Branch, SUM(Revenue) AS REVENUE
FROM NOVAKART_DB.ANALYTICS.SALES
GROUP BY Branch
ORDER BY REVENUE DESC;

-- Q8: Branches Generating Highest Profit
SELECT Branch, SUM(Profit) AS PROFIT
FROM NOVAKART_DB.ANALYTICS.SALES
GROUP BY Branch
ORDER BY PROFIT DESC;

-- Q9: Products with Low Inventory (Current_Stock < Minimum_Stock)
SELECT Inventory_ID, Product_ID, Warehouse, Current_Stock, Minimum_Stock
FROM NOVAKART_DB.ANALYTICS.INVENTORY
WHERE Current_Stock < Minimum_Stock;

-- Q10: Warehouses with Critical Stock
SELECT Warehouse, COUNT(*) AS CRITICAL_STOCK_COUNT
FROM NOVAKART_DB.ANALYTICS.INVENTORY
WHERE Stock_Status = 'Critical'
GROUP BY Warehouse
ORDER BY CRITICAL_STOCK_COUNT DESC;

-- Q11: Average Customer Order Value
SELECT ZEROIFNULL(ROUND(AVG(Revenue), 2)) AS AVG_CUSTOMER_ORDER_VALUE
FROM NOVAKART_DB.ANALYTICS.SALES;

-- Q12: Employees with Highest Performance Scores
SELECT Employee_ID, Name, Department, Role, Performance_Score, Salary
FROM NOVAKART_DB.ANALYTICS.EMPLOYEES
ORDER BY Performance_Score DESC, Salary DESC;

-- Q13: Total Finance Revenue, Expenses, Tax, and Net Profit
SELECT 
    SUM(Revenue) AS TOTAL_FINANCE_REVENUE,
    SUM(Expenses) AS TOTAL_FINANCE_EXPENSES,
    SUM(Tax) AS TOTAL_FINANCE_TAX,
    SUM(Net_Profit) AS TOTAL_FINANCE_NET_PROFIT
FROM NOVAKART_DB.ANALYTICS.FINANCE;

-- Q14: Percentage of Inventory Below Minimum Stock
SELECT ZEROIFNULL(ROUND((COUNT(CASE WHEN Current_Stock < Minimum_Stock THEN 1 END) / NULLIF(COUNT(*), 0)) * 100, 2)) AS PCT_BELOW_MINIMUM_STOCK
FROM NOVAKART_DB.ANALYTICS.INVENTORY;

-- Q15: Key Strategic Business Insights
-- (Summary Query: Combining Sales Performance & Inventory Risk)
SELECT 
    'Sales Revenue' AS METRIC, CAST(SUM(Revenue) AS VARCHAR) AS VALUE FROM NOVAKART_DB.ANALYTICS.SALES
UNION ALL
SELECT 'Sales Profit', CAST(SUM(Profit) AS VARCHAR) FROM NOVAKART_DB.ANALYTICS.SALES
UNION ALL
SELECT 'Low Stock Alert Items', CAST(COUNT(*) AS VARCHAR) FROM NOVAKART_DB.ANALYTICS.INVENTORY WHERE Current_Stock < Minimum_Stock
UNION ALL
SELECT 'Top Employee Performance Count (Score=5)', CAST(COUNT(*) AS VARCHAR) FROM NOVAKART_DB.ANALYTICS.EMPLOYEES WHERE Performance_Score = 5;

-- ============================================================================
-- PHASE 5: EXECUTIVE SUMMARY VIEW
-- ============================================================================

CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_EXECUTIVE_SUMMARY AS
SELECT 
    s.TOTAL_REVENUE,
    s.TOTAL_PROFIT,
    s.PROFIT_MARGIN_PCT,
    s.SALES_COUNT,
    s.AVG_ORDER_VALUE,
    c.CUSTOMER_COUNT,
    p.PRODUCT_COUNT,
    e.EMPLOYEE_COUNT,
    i.INVENTORY_ITEM_COUNT,
    i.CRITICAL_STOCK_COUNT,
    i.LOW_STOCK_COUNT
FROM 
    (SELECT 
        SUM(Revenue) AS TOTAL_REVENUE,
        SUM(Profit) AS TOTAL_PROFIT,
        ZEROIFNULL(ROUND((SUM(Profit) / NULLIF(SUM(Revenue), 0)) * 100, 2)) AS PROFIT_MARGIN_PCT,
        COUNT(*) AS SALES_COUNT,
        ZEROIFNULL(ROUND(AVG(Revenue), 2)) AS AVG_ORDER_VALUE
     FROM NOVAKART_DB.ANALYTICS.SALES) s
CROSS JOIN
    (SELECT COUNT(*) AS CUSTOMER_COUNT FROM NOVAKART_DB.ANALYTICS.CUSTOMERS) c
CROSS JOIN
    (SELECT COUNT(*) AS PRODUCT_COUNT FROM NOVAKART_DB.ANALYTICS.PRODUCTS) p
CROSS JOIN
    (SELECT COUNT(*) AS EMPLOYEE_COUNT FROM NOVAKART_DB.ANALYTICS.EMPLOYEES) e
CROSS JOIN
    (SELECT 
        COUNT(*) AS INVENTORY_ITEM_COUNT,
        COUNT(CASE WHEN Stock_Status = 'Critical' THEN 1 END) AS CRITICAL_STOCK_COUNT,
        COUNT(CASE WHEN Current_Stock < Minimum_Stock THEN 1 END) AS LOW_STOCK_COUNT
     FROM NOVAKART_DB.ANALYTICS.INVENTORY) i;

-- ============================================================================
-- PHASE 6: VALIDATION & VIEW AUDIT
-- ============================================================================

-- List all views in schema
SHOW VIEWS IN SCHEMA NOVAKART_DB.ANALYTICS;

-- Execute queries on all views to confirm data returning without errors
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_SALES_PROFIT_ANALYSIS;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_PRODUCT_PERFORMANCE;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_CUSTOMER_ANALYSIS;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_INVENTORY_ANALYSIS;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_FINANCE_SUMMARY;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_EMPLOYEE_ANALYSIS;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_RETAIL_KPI_SUMMARY;
SELECT * FROM NOVAKART_DB.ANALYTICS.VW_EXECUTIVE_SUMMARY;
