"""
Deploy Phase 2 Realtime Ingestion DDL to real Snowflake DWH.
"""

import snowflake.connector

conn = snowflake.connector.connect(
    user='RIXS',
    password='Riansalian@001',
    account='JQOFPHS-OZ81390',
    role='ACCOUNTADMIN',
    database='NOVAKART_DB',
    schema='ANALYTICS',
    warehouse='COMPUTE_WH'
)

cur = conn.cursor()

queries = [
    """CREATE OR REPLACE FILE FORMAT NOVAKART_DB.ANALYTICS.NOVAKART_CSV_FORMAT
    TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null') EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE;""",

    """CREATE TABLE IF NOT EXISTS NOVAKART_DB.ANALYTICS.RAW_SALES (
        SALE_ID VARCHAR(50), DATE DATE, CUSTOMER_ID VARCHAR(50), PRODUCT_ID VARCHAR(50),
        BRANCH VARCHAR(100), QUANTITY NUMBER, UNIT_PRICE NUMBER(12, 2), DISCOUNT NUMBER(12, 2),
        COST NUMBER(12, 2), REVENUE NUMBER(12, 2), PROFIT NUMBER(12, 2), VALIDATION_STATUS VARCHAR(50),
        LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );""",

    """CREATE TABLE IF NOT EXISTS NOVAKART_DB.ANALYTICS.REJECTED_RAW_SALES (
        SALE_ID VARCHAR(50), DATE DATE, CUSTOMER_ID VARCHAR(50), PRODUCT_ID VARCHAR(50),
        BRANCH VARCHAR(100), QUANTITY NUMBER, UNIT_PRICE NUMBER(12, 2), DISCOUNT NUMBER(12, 2),
        COST NUMBER(12, 2), REVENUE NUMBER(12, 2), PROFIT NUMBER(12, 2), VALIDATION_STATUS VARCHAR(50),
        REJECTION_REASON VARCHAR(255), QUARANTINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );""",

    """CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_STRATIFY_SALES_REALTIME AS
    SELECT SALE_ID, DATE, CUSTOMER_ID, PRODUCT_ID, BRANCH, QUANTITY, UNIT_PRICE, DISCOUNT, COST, REVENUE, PROFIT, VALIDATION_STATUS, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM NOVAKART_DB.ANALYTICS.SALES WHERE VALIDATION_STATUS = 'Valid'
    UNION ALL
    SELECT SALE_ID, DATE, CUSTOMER_ID, PRODUCT_ID, BRANCH, QUANTITY, UNIT_PRICE, DISCOUNT, COST, REVENUE, PROFIT, VALIDATION_STATUS, LOADED_AT
    FROM NOVAKART_DB.ANALYTICS.RAW_SALES WHERE VALIDATION_STATUS = 'Valid'
    AND SALE_ID NOT IN (SELECT SALE_ID FROM NOVAKART_DB.ANALYTICS.SALES);""",

    """CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_STRATIFY_REALTIME_KPI AS
    SELECT COALESCE(SUM(REVENUE), 0) AS TOTAL_REVENUE, COALESCE(SUM(PROFIT), 0) AS TOTAL_PROFIT,
    ZEROIFNULL(ROUND((SUM(PROFIT) / NULLIF(SUM(REVENUE), 0)) * 100, 2)) AS PROFIT_MARGIN_PCT,
    COUNT(SALE_ID) AS TOTAL_TRANSACTIONS, COALESCE(SUM(QUANTITY), 0) AS TOTAL_QUANTITY,
    ZEROIFNULL(ROUND(AVG(REVENUE), 2)) AS AVERAGE_ORDER_VALUE, MAX(LOADED_AT) AS LAST_TRANSACTION_TIME
    FROM NOVAKART_DB.ANALYTICS.VW_STRATIFY_SALES_REALTIME;""",

    """CREATE OR REPLACE VIEW NOVAKART_DB.ANALYTICS.VW_STRATIFY_DATA_FRESHNESS AS
    SELECT MAX(LOADED_AT) AS LAST_TRANSACTION_TIME,
    DATEDIFF(second, MAX(LOADED_AT), CURRENT_TIMESTAMP()) AS DATA_FRESHNESS_SECONDS,
    CASE WHEN DATEDIFF(second, MAX(LOADED_AT), CURRENT_TIMESTAMP()) <= 60 THEN 'FRESH (<1m)'
         WHEN DATEDIFF(second, MAX(LOADED_AT), CURRENT_TIMESTAMP()) <= 300 THEN 'MODERATE (<5m)'
         ELSE 'STALE (>5m)' END AS FRESHNESS_STATUS
    FROM NOVAKART_DB.ANALYTICS.VW_STRATIFY_SALES_REALTIME;"""
]

for idx, q in enumerate(queries):
    print(f"Executing DDL {idx+1}/{len(queries)}...")
    cur.execute(q)
    print(f"DDL {idx+1} SUCCESS!")

conn.close()
print("🎉 ALL DDL OBJECTS SUCCESSFULLY CREATED ON REAL SNOWFLAKE WAREHOUSE!")
